set_property PACKAGE PIN W30[get_ports R3_A2]
set_property PACKAGE PIN V27[get_ports TTT14]
set_property PACKAGE PIN W28[get_ports TTT12]
set_property PACKAGE_ PIN W25[get_ports TTT10]
set_property PACKAGE_ PIN W26[get_ports TTT11]
set_property PACKAGE PIN U25[get_ports TTT_CLK1] 
